/**
 * MAIN SITEMAP (Next.js 15 - app router)
 * 
 * This is the primary sitemap generated by your app.
 * Deploy to: /public/sitemap.xml (or use sitemap.ts in app/ directory)
 * 
 * Includes all routes with locale variants and hreflang alternates.
 * Automatically includes locale-specific sitemaps via sitemap index.
 */

import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.alidrisy.com';
  const locales = ['en', 'ar'];
  const lastModified = new Date();

  // Define all main routes
  const routes = [
    {
      path: '',
      priority: 1.0,
      changeFrequency: 'weekly' as const,
    },
    {
      path: '/about',
      priority: 0.9,
      changeFrequency: 'monthly' as const,
    },
    {
      path: '/services',
      priority: 0.9,
      changeFrequency: 'monthly' as const,
    },
    {
      path: '/projects',
      priority: 0.9,
      changeFrequency: 'weekly' as const,
    },
    {
      path: '/contact',
      priority: 0.8,
      changeFrequency: 'yearly' as const,
    },
    {
      path: '/faq',
      priority: 0.7,
      changeFrequency: 'monthly' as const,
    },
  ];

  // Generate sitemap entries for all locales with hreflang alternates
  const sitemapEntries: MetadataRoute.Sitemap = [];

  locales.forEach((locale) => {
    routes.forEach((route) => {
      const url = `${baseUrl}/${locale}${route.path}`;
      
      sitemapEntries.push({
        url: url,
        lastModified: lastModified,
        changeFrequency: route.changeFrequency,
        priority: route.priority,
        // Add hreflang alternates for each URL
        alternates: {
          languages: {
            en: `${baseUrl}/en${route.path}`,
            ar: `${baseUrl}/ar${route.path}`,
            'x-default': `${baseUrl}/en${route.path}`,
          },
        },
      });
    });
  });

  return sitemapEntries;
}
